# Generated by Django 2.2 on 2020-08-07 21:07

import ajaximage.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=ajaximage.fields.AjaxImageField(),
        ),
    ]
