# Generated by Django 2.2 on 2020-08-08 07:43

import ajaximage.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200808_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=ajaximage.fields.AjaxImageField(blank=True, default='robot.png', null=True),
        ),
    ]
