# Generated by Django 2.2 on 2020-08-10 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200808_0949'),
        ('post', '0004_auto_20200808_1043'),
    ]

    operations = [
    ]
